// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: gate/v1/gate.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: dc:"注册服务" v:"required"
	RegService string `protobuf:"bytes,1,opt,name=reg_service,json=regService,proto3" json:"reg_service,omitempty" dc:"@inject_tag: dc:'注册服务' v:'required'注册服务 v:'required' json:'reg_service'"` // 注册服务 v:"required" json:"reg_service"
	// @inject_tag: dc:"服务名" v:"required"
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty" dc:"@inject_tag: dc:'服务名' v:'required'服务名"` // 服务名
	// @inject_tag: dc:"方法名" v:"required"
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty" dc:"@inject_tag: dc:'方法名' v:'required'"`
	// @inject_tag: json:"access_token" dc:"参数，JSON 字符串"
	Payload       string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty" dc:"@inject_tag: json:'access_token' dc:'参数，JSON 字符串'参数，JSON 字符串"` // 参数，JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_gate_v1_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate_v1_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_gate_v1_gate_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetRegService() string {
	if x != nil {
		return x.RegService
	}
	return ""
}

func (x *CallRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CallReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty" dc:"返回值，JSON 字符串"` // 返回值，JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallReply) Reset() {
	*x = CallReply{}
	mi := &file_gate_v1_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReply) ProtoMessage() {}

func (x *CallReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_v1_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReply.ProtoReflect.Descriptor instead.
func (*CallReply) Descriptor() ([]byte, []int) {
	return file_gate_v1_gate_proto_rawDescGZIP(), []int{1}
}

func (x *CallReply) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_gate_v1_gate_proto protoreflect.FileDescriptor

const file_gate_v1_gate_proto_rawDesc = "" +
	"\n" +
	"\x12gate/v1/gate.proto\x12\x04gate\"z\n" +
	"\vCallRequest\x12\x1f\n" +
	"\vreg_service\x18\x01 \x01(\tR\n" +
	"regService\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"%\n" +
	"\tCallReply\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload22\n" +
	"\x04Gate\x12*\n" +
	"\x04Call\x12\x11.gate.CallRequest\x1a\x0f.gate.CallReplyB!Z\x1fmiddle_gate/app/rpc/api/gate/v1b\x06proto3"

var (
	file_gate_v1_gate_proto_rawDescOnce sync.Once
	file_gate_v1_gate_proto_rawDescData []byte
)

func file_gate_v1_gate_proto_rawDescGZIP() []byte {
	file_gate_v1_gate_proto_rawDescOnce.Do(func() {
		file_gate_v1_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_v1_gate_proto_rawDesc), len(file_gate_v1_gate_proto_rawDesc)))
	})
	return file_gate_v1_gate_proto_rawDescData
}

var file_gate_v1_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gate_v1_gate_proto_goTypes = []any{
	(*CallRequest)(nil), // 0: gate.CallRequest
	(*CallReply)(nil),   // 1: gate.CallReply
}
var file_gate_v1_gate_proto_depIdxs = []int32{
	0, // 0: gate.Gate.Call:input_type -> gate.CallRequest
	1, // 1: gate.Gate.Call:output_type -> gate.CallReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gate_v1_gate_proto_init() }
func file_gate_v1_gate_proto_init() {
	if File_gate_v1_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_v1_gate_proto_rawDesc), len(file_gate_v1_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gate_v1_gate_proto_goTypes,
		DependencyIndexes: file_gate_v1_gate_proto_depIdxs,
		MessageInfos:      file_gate_v1_gate_proto_msgTypes,
	}.Build()
	File_gate_v1_gate_proto = out.File
	file_gate_v1_gate_proto_goTypes = nil
	file_gate_v1_gate_proto_depIdxs = nil
}
